export const productosData = {
  productos: [
    {
      nombre: "Dona Triple Chocolate",
      precio: 35,
      cantidad_existente: 50,
      tamaño: "90 g - Porción Individual",
      descripcion_producto:
        "Una dona suave y esponjosa bañada en una rica cobertura de chocolate y decorada con chispas de chocolate para un extra de dulzura y textura.",
      perfecto_para: "Acompañar tu bebida favorita.",
      imagen: "dona_triple_chocolate.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre:
        "El chocolate en todas sus formas, en un solo bocado. ❤️",
    },
    {
      nombre: "Brownie en Taza",
      precio: 60,
      cantidad_existente: 30,
      tamaño: "150 g - Porción Individual",
      descripcion_producto:
        "Un postre calientito y reconfortante: brownie de chocolate servido en taza, coronado con una capa cremosa y decorado con chispas de chocolate que se derriten suavemente.",
      perfecto_para: "Disfrutar en cualquier ocasión.",
      imagen: "brownie_en_taza.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: true,
      de_temporada: false,
      frase_de_cierre: "El sabor casero que abraza el alma. ❤️",
    },
    {
      nombre: "Frappé de Chocolate",
      precio: 70,
      cantidad_existente: 40,
      tamaño: "400 ml - Porción Individual",
      descripcion_producto:
        "Una explosión refrescante de chocolate en cada sorbo. Preparado con cacao de alta calidad, leche y hielo, coronado con crema batida y chispas de chocolate para un toque final irresistible.",
      perfecto_para: "Los amantes del chocolate en días calurosos.",
      imagen: "frappe_de_chocolate.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "El lado más refrescante del cacao. ❤️",
    },
    {
      nombre: "Chocolate Oaxaqueño Caliente",
      precio: 45,
      cantidad_existente: 20,
      tamaño: "300 ml - Porción Individual",
      descripcion_producto:
        "Una taza de tradición y calidez, preparado con cacao artesanal, especias y un toque de amor que honra la esencia de Oaxaca.",
      perfecto_para: "Disfrutar momentos acogedores.",
      imagen: "chocolate_oaxaqueno_caliente.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "El sabor auténtico que conecta con tus raíces. ❤️",
    },
    {
      nombre: "Pastelillo de Corazón para San Valentín",
      precio: 65,
      cantidad_existente: 15,
      tamaño: "120 g - Porción Individual",
      descripcion_producto:
        "Un delicioso pastelillo en forma de corazón, cubierto de perlas de chocolate y relleno cremoso de avellanas.",
      perfecto_para: "Regalar amor en cada mordida.",
      imagen: "pastelillo_san_valentin.jpg",
      descuento: 10,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-20",
      nuevo: true,
      de_temporada: true,
      frase_de_cierre:
        "Ideal para celebrar momentos especiales y endulzar corazones. ❤️",
    },
    {
      nombre: "Café Moka con Crema Batida (Caliente)",
      precio: 55,
      cantidad_existente: 25,
      tamaño: "300 ml - Porción Individual",
      descripcion_producto:
        "Un clásico indulgente que combina el sabor intenso del espresso con el toque dulce del chocolate, coronado con crema batida.",
      perfecto_para: "Un momento de relajación o inspiración.",
      imagen: "cafe_moka_caliente.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "Un abrazo en cada sorbo. ☕🍫",
    },
    {
      nombre: "Café Cortado con Crema Batida",
      precio: 50,
      cantidad_existente: 30,
      tamaño: "200 ml - Porción Individual",
      descripcion_producto:
        "El equilibrio perfecto entre la fuerza del espresso y la suavidad de la crema batida.",
      perfecto_para: "Acompañar tu día con estilo.",
      imagen: "cafe_cortado.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "Pequeño en tamaño, grande en sabor. ❤️☕",
    },
    {
      nombre: "Café Frío Espumoso de Caramelo + Fresa con Crema Batida",
      precio: 65,
      cantidad_existente: 20,
      tamaño: "400 ml - Porción Individual",
      descripcion_producto:
        "Una bebida refrescante que combina el café con notas dulces de caramelo y fresa, coronado con crema batida.",
      perfecto_para: "Los amantes de lo dulce y lo original.",
      imagen: "cafe_frio_espumoso.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "Un deleite frío y lleno de sabor. ❄️☕🍓",
    },
    {
      nombre: "Panqué de Chocolate con Frutos Rojos",
      precio: 55,
      cantidad_existente: 25,
      tamaño: "120 g - Porción Individual",
      descripcion_producto:
        "Un panqué suave y esponjoso con el intenso sabor del chocolate, acompañado de frutos rojos frescos.",
      perfecto_para: "Un desayuno especial o un snack único.",
      imagen: "panque_chocolate_frutos_rojos.jpg",
      descuento: 0,
      fecha_actualizacion: "2025-01-27",
      disponible: true,
      fecha_registro: "2025-01-01",
      nuevo: false,
      de_temporada: false,
      frase_de_cierre: "Chocolate y frutos rojos, la combinación perfecta. ❤",
    },
  ],
};
